/* eslint-disable */
/**
 * AUTO-GENERATED by aura/api/scripts/gen_api_types.py — 勿手改。
 * 契约唯一真源：FastAPI openapi（app/schemas.py）。
 * 再生成：cd aura/api && .venv/bin/python scripts/gen_api_types.py
 */
export interface AnalyzeData {
  product: ProductBrief
  oxidation: Oxidation
  verdict: Verdict
  ingredients: Array<IngredientRow>
  panel: Panel
  vision: VisionSpec
  synesthesia: Synesthesia
}

export interface AnalyzeRequest {
  product_id: string
  population?: "healthy" | "sensitive" | "pregnant" | "rhinitis" | "anosmic" | undefined
  opened_months?: number | undefined
  storage?: "cool" | "room" | "hot" | undefined
  mode?: "normal" | "anosmia" | "sensitive" | undefined
}

export interface AnalyzeResponse {
  data?: AnalyzeData | null
  meta: Meta
}

export interface BarcodeRequest {
  code: string
}

export interface Candidate {
  id: string
  brand: string
  name: string
  tag?: string | undefined
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>
}

export interface HealthData {
  status: string
  engine: string
  perfumes: number
  ifra_limits: number
  ifra_banned: number
  dictEntries: number
}

export interface HealthResponse {
  data: HealthData
  meta: Meta
}

export interface ImageRecognitionResponse {
  data: RecognitionResult
  meta: Meta
}

export interface ImageRequest {
  /** dataURL 或纯 base64 */
  image: string
  /** 文件名（mock 确定性哈希用） */
  filename?: string | undefined
}

export interface IngredientRow {
  inci: string
  zh: string
  conc: string
  level: "low" | "mid" | "high"
  gate: string
  evidence: "documented" | "indicative" | "insufficient"
  note: string
  limitPct?: number | null
}

export interface Meta {
  request_id?: string | undefined
  engine?: string | undefined
  models?: MetaModels
  degraded?: MetaDegraded
  error?: string | null
  seed?: number | null
}

export interface MetaDegraded {
  vision?: boolean | undefined
  reason?: string | undefined
}

export interface MetaModels {
  synesthesia?: string | undefined
  recognition?: string | undefined
}

export interface Oxidation {
  d: number
  months: number
  storage: string
}

export interface Panel {
  label: string
  name: string
  concPct: number
  ael: number | null
  p50: number | null
  p90: number | null
  p99: number | null
  marginPoint: number | null
  marginP99: number | null
  marginPolicy: number | null
  policy: string
  tPop: number
}

export interface ProductBrief {
  id: string
  brand: string
  name: string
  en?: string | undefined
  familyZh?: string | undefined
  concentration?: string | undefined
}

export interface ProductsResponse {
  data: Array<ProductBrief>
  meta: Meta
}

export interface RadarPoint {
  dim: string
  v: number
}

export interface RecognitionResult {
  status: "ok" | "confirm" | "error"
  confidence?: number | undefined
  product?: ProductBrief | null
  candidates?: Array<Candidate> | undefined
  provider?: string | undefined
  note?: string | undefined
  error?: string | undefined
}

export interface SpecLayer {
  layer: string
  weight: number
  color: string
  notes: Array<SpecNote>
}

export interface SpecMixItem {
  family: string
  share: number
  color: string
  mood: string
  scene: string
  shape: string
}

export interface SpecNote {
  name: string
  family: string
  color: string
  pct: number
}

export interface Synesthesia {
  text: string
  model: string
  isLlm: boolean
}

export interface ValidationError {
  loc: Array<string>
  msg: string
  type: string
  input?: unknown
  ctx?: Record<string, unknown>
}

export interface Verdict {
  level: "low" | "mid" | "high"
  headline: string
  reasons: Array<string>
  advice: string
  dominantGate: string
  hits: string
}

export interface VisionSpec {
  degraded: boolean
  degradeReason?: string | undefined
  primary?: string | undefined
  secondary?: string | undefined
  gradient?: string | undefined
  layers?: Array<SpecLayer> | undefined
  mix?: Array<SpecMixItem> | undefined
  moodWords?: string | undefined
  radar?: Array<RadarPoint> | undefined
}
