#!/usr/bin/env python3
"""从 FastAPI openapi 生成前端 TS 类型（P1-5：契约单一真源，前端零手写类型）

用法：cd aura/api && .venv/bin/python scripts/gen_api_types.py
输出：aura/web/src/lib/api-types.ts（文件头带 AUTO-GENERATED，勿手改）
"""

from __future__ import annotations

import sys
from pathlib import Path

API_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(API_ROOT))

from app.main import app  # noqa: E402

OUT = API_ROOT.parent / "web" / "src" / "lib" / "api-types.ts"

TS_MAP = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean"}


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "anyOf" in schema:
        parts = [ts_type(s) for s in schema["anyOf"] if not (s.get("type") == "null")]
        nullable = any(s.get("type") == "null" for s in schema["anyOf"])
        base = parts[0] if parts else "unknown"
        return f"{base} | null" if nullable else base
    t = schema.get("type")
    if t == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if t == "object":
        return "Record<string, unknown>"
    if "enum" in schema:
        return " | ".join(f'"{v}"' for v in schema["enum"])
    return TS_MAP.get(t, "unknown")


def render() -> str:
    spec = app.openapi()
    schemas = spec.get("components", {}).get("schemas", {})
    blocks = []
    for name, sc in schemas.items():
        required = set(sc.get("required", []))
        lines = [f"export interface {name} {{"]
        for prop, ps in sc.get("properties", {}).items():
            ty = ts_type(ps)
            if prop not in required and None not in (ps.get("type"),) and "default" in ps:
                ty = f"{ty} | undefined" if prop not in required else ty
            opt = "" if prop in required else "?"
            desc = ps.get("description", "")
            comment = f"  /** {desc} */\n" if desc else ""
            lines.append(f"{comment}  {prop}{opt}: {ty}")
        lines.append("}")
        blocks.append("\n".join(lines))
    header = (
        "/* eslint-disable */\n"
        "/**\n"
        " * AUTO-GENERATED by aura/api/scripts/gen_api_types.py — 勿手改。\n"
        " * 契约唯一真源：FastAPI openapi（app/schemas.py）。\n"
        " * 再生成：cd aura/api && .venv/bin/python scripts/gen_api_types.py\n"
        " */\n"
    )
    return header + "\n\n".join(blocks) + "\n"


def main() -> None:
    text = render()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    n = text.count("export interface")
    print(f"✓ {OUT}（{n} 个接口）")


if __name__ == "__main__":
    main()
